name: awtos
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  dio: ^5.3.2
  flutter:
    sdk: flutter
  flutter_polyline_points: ^2.0.0
  geocoding: ^2.1.0
  get: ^4.6.6
  google_maps_flutter: ^2.5.0
  google_maps_flutter_web: ^0.5.4+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
   

  fonts:
    - family: Raleway
      fonts:
        - asset: fonts/Raleway-Bold.ttf
        - asset: fonts/Raleway-Medium.ttf
        - asset: fonts/Raleway-Regular.ttf
        - asset: fonts/Raleway-SemiBold.ttf
          

